# Generated by Django 3.2.7 on 2021-09-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('SSN', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='SSN')),
                ('Name', models.CharField(blank=True, max_length=15)),
                ('phone', models.PositiveIntegerField(blank=True)),
                ('Is_owner', models.BooleanField(blank=True, default=True)),
                ('Can_sign_contract', models.BooleanField(default=True)),
                ('Can_sell_car', models.BooleanField(default=True)),
                ('Can_change_price', models.BooleanField(default=True)),
            ],
        ),
    ]
