# Generated by Django 3.2.7 on 2021-09-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealershop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='Can_change_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='Can_sell_car',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='Can_sign_contract',
            field=models.BooleanField(default=False),
        ),
    ]
