# Generated by Django 3.2.7 on 2021-09-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealershop', '0002_auto_20210917_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateTimeField(auto_now_add=True)),
                ('End_Date', models.DateTimeField(auto_now_add=True)),
                ('Dealers', models.ManyToManyField(blank=True, related_name='Contract', to='dealershop.Dealers')),
            ],
        ),
    ]
