# Generated by Django 3.2.7 on 2021-09-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealershop', '0006_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='Dealers',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Industries',
        ),
    ]
