# Generated by Django 3.2.7 on 2021-09-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealershop', '0011_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='Dealers',
        ),
        migrations.AddField(
            model_name='dealers',
            name='Can_buy_car',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='Is_owner',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='SSN',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='SSN'),
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Industries',
        ),
    ]
