# Generated by Django 3.2.7 on 2021-09-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealershop', '0022_remove_cars_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
