# Generated by Django 3.2.7 on 2021-09-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealershop', '0024_cars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
